services:
  registry:
    image: registry:2
    ports:
      - "5001:5000"

  grafana:
    image: grafana/grafana:11.2.0
    attach: false
    ports:
      - 5050:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./rootfs/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./rootfs/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./rootfs/grafana/dashboards:/dashboards
    depends_on:
      - loki
      - prometheus
      - tempo

  tempo:
    image: grafana/tempo:2.6.0
    attach: false
    command:
      - "-config.file=/config.yaml"
    volumes:
      - ./rootfs/tempo/config.yaml:/config.yaml
    ports:
      - 4318 # This port is used for sending traces from otel-collector to tempo
      - 7999:7999 # tempo

  loki:
    image: grafana/loki:3.0.1
    attach: false
    command:
      - "-config.file=/config.yaml"
    volumes:
      - ./rootfs/loki/config.yaml:/config.yaml
    ports:
      - 3100:3100
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    attach: false
    command:
      - "--config.file=/config.yaml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
    volumes:
      - ./rootfs/prometheus/config.yaml:/config.yaml
    ports:
      - 9090:9090
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0
    depends_on:
      - loki
      - tempo
      - prometheus
    command:
      - "--config=/otel-collector/otel-config.yaml"
      - "--feature-gates=-component.UseLocalHostAsDefaultHost"
    volumes:
      - ./rootfs/otel-collector:/otel-collector

  nats:
    image: nats:2-alpine
    attach: false
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1:4222"]
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 2s
      start_interval: 2s
    command:
      - "-js"
    ports:
      - 4222:4222

  wadm:
    image: ghcr.io/wasmcloud/wadm:v0.14.0
    depends_on:
      nats:
        condition: service_healthy
    environment:
      WADM_NATS_SERVER: nats:4222

  wasmcloud-host-north:
    image: ghcr.io/wasmcloud/wasmcloud:1.2.1
    attach: false
    depends_on:
      nats:
        condition: service_healthy
      otel-collector:
        condition: service_started
    command:
      - wasmcloud
      - "--override-observability-endpoint=http://otel-collector:4318"
    environment:
      WASMCLOUD_OCI_ALLOW_LATEST: "true"
      WASMCLOUD_NATS_HOST: nats
      WASMCLOUD_NATS_PORT: "4222"
      WASMCLOUD_LABEL_location: north
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: "registry:5000"

  wasmcloud-host-south:
    image: ghcr.io/wasmcloud/wasmcloud:1.2.1
    attach: false
    depends_on:
      nats:
        condition: service_healthy
      otel-collector:
        condition: service_started
    command:
      - wasmcloud
      - "--override-observability-endpoint=http://otel-collector:4318"
    environment:
      WASMCLOUD_OCI_ALLOW_LATEST: "true"
      WASMCLOUD_NATS_HOST: nats
      WASMCLOUD_NATS_PORT: "4222"
      WASMCLOUD_LABEL_location: south
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: "registry:5000"

  wasmcloud-host-east:
    image: ghcr.io/wasmcloud/wasmcloud:1.2.1
    attach: false
    depends_on:
      nats:
        condition: service_healthy
      otel-collector:
        condition: service_started
    command:
      - wasmcloud
      - "--override-observability-endpoint=http://otel-collector:4318"
    environment:
      WASMCLOUD_OCI_ALLOW_LATEST: "true"
      WASMCLOUD_NATS_HOST: nats
      WASMCLOUD_NATS_PORT: "4222"
      WASMCLOUD_LABEL_location: east
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: "registry:5000"

  wasmcloud-host-west:
    image: ghcr.io/wasmcloud/wasmcloud:1.2.1
    attach: false
    depends_on:
      nats:
        condition: service_healthy
      otel-collector:
        condition: service_started
    command:
      - wasmcloud
      - "--override-observability-endpoint=http://otel-collector:4318"
    environment:
      RUST_LOG: debug,hyper=info,async_nats=info,oci_distribution=info,cranelift_codegen=warn
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      WASMCLOUD_OCI_ALLOW_LATEST: "true"
      WASMCLOUD_NATS_HOST: nats
      WASMCLOUD_NATS_PORT: "4222"
      WASMCLOUD_LABEL_location: west
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: "registry:5000"

  wasmcloud-host-control:
    image: ghcr.io/wasmcloud/wasmcloud:1.2.1
    depends_on:
      nats:
        condition: service_healthy
      otel-collector:
        condition: service_started
    command:
      - wasmcloud
      # missing in env
      - "--override-observability-endpoint=http://otel-collector:4318"
    environment:
      WASMCLOUD_OCI_ALLOW_LATEST: "true"
      WASMCLOUD_NATS_HOST: nats
      WASMCLOUD_NATS_PORT: "4222"
      WASMCLOUD_LABEL_location: control
      WASMCLOUD_OBSERVABILITY_ENABLED: "true"
      WASMCLOUD_OCI_ALLOWED_INSECURE: "registry:5000"
    ports:
      - 30000:30000
