apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: lwc-demo
  annotations:
    description: "Component Ring"
    wasmcloud.dev/authors: wasmCloud team
spec:
  components:
    - name: north
      type: component
      properties:
        image: registry:5000/lwc_probe:latest
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: primary
                requirements:
                  location: north
        - type: link
          properties:
            name: default
            target: west
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]
        - type: link
          properties:
            name: special
            target: south
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]

    - name: south
      type: component
      properties:
        image: registry:5000/lwc_probe:latest
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: primary
                requirements:
                  location: south
        - type: link
          properties:
            name: default
            target: east
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]
        - type: link
          properties:
            name: special
            target: east
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]

    - name: east
      type: component
      properties:
        image: registry:5000/lwc_probe:latest
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: primary
                requirements:
                  location: east
        - type: link
          properties:
            name: default
            target: north
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]
        - type: link
          properties:
            name: special
            target: west
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]

    - name: west
      type: component
      properties:
        image: registry:5000/lwc_probe:latest
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: primary
                requirements:
                  location: west
        - type: link
          properties:
            name: default
            target: south
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]
        - type: link
          properties:
            name: special
            target: north
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]

    - name: control-center
      type: component
      properties:
        image: registry:5000/lwc_control_center:latest
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: primary
                requirements:
                  location: control
        - type: link
          properties:
            name: default
            target: east
            namespace: wasmcloud
            package: lwc
            interfaces: [packet-looper]

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: primary
                requirements:
                  location: control
        - type: link
          properties:
            target: control-center
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:30000
