server:
  http_listen_port: 7999
  grpc_server_max_recv_msg_size: 29000000
  grpc_server_max_send_msg_size: 29000000

distributor:
  log_received_spans:
    enabled: true
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4318"

storage:
  trace:
    backend: local
    block:
      v2_encoding: zstd
    wal:
      path: /tmp/tempo/wal
      v2_encoding: none
    local:
      path: /tmp/tempo/blocks

overrides:
  defaults:
    ingestion:
      max_traces_per_user: 0
